#!/bin/sh

# Prints the current volume or 🔇 if muted.
[ $(pamixer --get-mute) = true ] && echo "ﱝ" && exit

re='^[0-9]+$'
vol="$(pamixer --get-volume)"
while ! [[ $vol =~ $re ]]
do
    vol="$(pamixer --get-volume)"
done

if [ "$vol" -gt "66" ]; then
	icon="墳"
elif [ "$vol" -gt "33" ]; then
	icon="奔"
elif [ "$vol" -gt "1" ]; then
	icon="奄"
else
	icon="婢"
fi

echo "$icon $vol"
